"""stored_files: add storage_key, make data nullable (R2 Phase 1)

Revision ID: i7d8e9f0a1b2
Revises: h6c7d8e9f0a1
Create Date: 2026-09-28 00:00:00.000000

Phase 1 of the PlanetScale + Cloudflare R2 migration. This is schema-only —
no row is touched, no data is moved. Every existing row keeps `storage_key
NULL` and its `data` exactly as it is; `app/core/files.py::get_bytes()`
already treats that as "served from the database," identical to today's
behavior. Only once `app/scripts/move_files_to_r2.py` actually runs (a
separate, explicit Phase 2 step, not part of this migration) does any row
get `storage_key` set and `data` cleared.

Hand-written rather than autogenerated, per this project's Alembic policy
(see alembic/README): every operation is guarded with an existence check
against the live schema, so re-running this migration — or running it
against a database some other path already brought up to date — is a safe
no-op, not an error.
"""
import logging
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'i7d8e9f0a1b2'
down_revision: Union[str, Sequence[str], None] = 'h6c7d8e9f0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = logging.getLogger("alembic.runtime.migration")

_TABLE = "stored_files"


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if _TABLE not in inspector.get_table_names():
        # Fresh database: Base.metadata.create_all() / the baseline revision
        # already creates this table from the current model (storage_key
        # present, data nullable) — nothing to alter.
        return

    columns = {c["name"]: c for c in inspector.get_columns(_TABLE)}

    if "storage_key" not in columns:
        logger.info("Adding %s.storage_key", _TABLE)
        with op.batch_alter_table(_TABLE) as batch_op:
            batch_op.add_column(sa.Column("storage_key", sa.String(length=500), nullable=True))
            batch_op.create_index(f"ix_{_TABLE}_storage_key", ["storage_key"])
    else:
        logger.info("%s.storage_key already exists — skipping add", _TABLE)

    if not columns.get("data", {}).get("nullable", True):
        logger.info("Dropping NOT NULL on %s.data", _TABLE)
        with op.batch_alter_table(_TABLE) as batch_op:
            batch_op.alter_column("data", existing_type=sa.LargeBinary(), nullable=True)
    else:
        logger.info("%s.data is already nullable (or table is new) — skipping", _TABLE)


def downgrade() -> None:
    """Reverses the column add unconditionally, but only restores `data`'s
    NOT NULL constraint if it is actually safe to: if any row already has
    `data IS NULL` (meaning its bytes now live in R2 — app/scripts/
    move_files_to_r2.py has run), restoring NOT NULL would either fail
    outright or silently destroy the fact that row is R2-backed. In that
    case this leaves `data` nullable and logs a warning rather than guessing
    — there is no safe automatic way to "downgrade" a row whose bytes are no
    longer in this database at all.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if _TABLE not in inspector.get_table_names():
        return

    columns = {c["name"]: c for c in inspector.get_columns(_TABLE)}

    if "storage_key" in columns:
        null_data_count = bind.execute(
            sa.text(f'SELECT COUNT(*) FROM "{_TABLE}" WHERE data IS NULL')
        ).scalar()
        if null_data_count:
            logger.warning(
                "%s: %d row(s) have data IS NULL (bytes live in R2) — leaving data "
                "nullable; NOT NULL cannot be safely restored without either losing "
                "those rows' content or re-downloading it from R2 first. Dropping "
                "storage_key only.",
                _TABLE, null_data_count,
            )
            with op.batch_alter_table(_TABLE) as batch_op:
                batch_op.drop_index(f"ix_{_TABLE}_storage_key")
                batch_op.drop_column("storage_key")
            return

        logger.info("Dropping %s.storage_key and restoring NOT NULL on data", _TABLE)
        with op.batch_alter_table(_TABLE) as batch_op:
            batch_op.drop_index(f"ix_{_TABLE}_storage_key")
            batch_op.drop_column("storage_key")
            batch_op.alter_column("data", existing_type=sa.LargeBinary(), nullable=False)
    else:
        logger.info("%s.storage_key already absent — nothing to drop", _TABLE)
